# Generated by Django 3.2.8 on 2021-12-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=999)),
                ('due_date', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
